### ISSUE TITLE
Error 403 failed to set up

### ISSUE THREAD

**Issue by carealtor** [dreed47/redfin#16]
I've tried to re-install Redfin several times over the last several days.  Never works and I get error 403 and failed to set up.
![Screenshot 2025-01-01 184416](https://github.com/user-attachments/assets/9869bb02-d0e1-44b2-82a6-c8f688ec2c92)
![Screenshot 2025-01-01 184244](https://github.com/user-attachments/assets/9277af87-dd07-44c3-8856-40207c95f26b)

**Comment by foxalerts23** [comment]
Same.
Deleted, restarted, added and get error 403.

**Comment by broyuken** [comment]
add me to that list as well

**Comment by bindedig** [comment]
add me to that list as well

**Comment by gourdo1** [comment]
Broken for me with 403 errors as of Jan 10, 2025.

**Comment by broyuken** [comment]
@dreed47 isnt developing this anymore, it’s dead and gonna be removed from hacs

**Comment by gourdo1** [comment]
FWIW, my quick and dirty workaround for this integration being abandoned is to use a NodeRed Exec node with the below command line and push the result into a sensor node:

curl -k -L "_{YOUR_PROPERTY'S_REDFIN_URL}_" -A "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:134.0) Gecko/20100101 Firefox/134.0" | grep -E -o '"predicted_value".{20}' | cut -d: -f2 | cut -d, -f1

**Comment by kzaoaai** [comment]
> curl -k -L "_{YOUR_PROPERTY'S_REDFIN_URL}_" -A "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:134.0) Gecko/20100101 Firefox/134.0" | grep -E -o '"predicted_value".{20}' | cut -d: -f2 | cut -d, -f1

Thanks for the inspiration. I created a simple command_line sensor based on it.
```
  - sensor:
      name: Redfin Price
      unique_id: redfin_price
      command: >
        curl -k -L '{URL_GOES_HERE}' -A 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:134.0) Gecko/20100101 Firefox/134.0' | grep -E -o '\"predicted_value\".{20}' | cut -d: -f2 | cut -d, -f1 | awk '{if ($1 > 0) print $1; else print "ERROR"}'
      device_class: monetary
      unit_of_measurement: "$"
      scan_interval: 86400
```
