### ISSUE TITLE
Recommended Lovelace card?

### ISSUE THREAD

**Issue by mgriffin13** [dreed47/redfin#4]
Do you have a recommended Lovelace card to display the data?

I've started looking at something like this

```yaml
type: grid
cards:
  - type: picture-glance
    entities: []
    camera_image: camera.redfin
  - type: entities
    entities:
      - entity: sensor.redfin_house
        name: House
        secondary_info: last-updated
columns: 1
square: false
```

Tangentially, it would be real cool if the integration created a `generic camera entity` automatically for the `street view` URL image so I wouldn't need to manage it myself.
